markdown: rdiscount
pygments: false
permalink: /articles/:title
exclude: ["readme.md", "Gemfile", "Gemfile.lock", "config.ru"]
name: MSKCC Patient Education
description: MSKCC Patient Education
url: http://patiented.com

# this goes inside _config.yml. Change as required
navigation:
- text: Articles
  url: /articles/index.html
  cleanurl: /articles/
  layout: default
- text: Strategy
  url: /strategy/index.html
  cleanurl: /strategy/
  layout: default
secondary:
- text: RSS
  url: /feed.xml
  cleanurl: /feed.xml
  layout: default
